"""
Django settings for woodora project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets and connection strings live in .env (never committed).
# See .env.example for the keys this project expects.
load_dotenv(BASE_DIR / '.env')


def env(name, default=None, required=False):
    value = os.environ.get(name, default)
    if required and not value:
        raise RuntimeError(
            f"{name} is not set. Copy .env.example to .env and fill it in."
        )
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', 'django-insecure-f+9j1s+awv%vc(@v6cqay!k+-k)7t+$kl=lrc8retu==%rh+n-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver'] + [
    h for h in env('ALLOWED_HOSTS', '').split(',') if h
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files in production; no-op behind a CDN.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'woodora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalog.context_processors.nav_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'woodora.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Supabase Postgres. Use the *session pooler* / direct connection string from
# Supabase -> Project Settings -> Database, not the transaction pooler, so that
# migrations and full-text search work normally.
DATABASES = {
    'default': dj_database_url.parse(
        env('DATABASE_URL', required=True),
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic writes here; WhiteNoise serves from it.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ---------------------------------------------------------------------------
# Supabase Storage (S3-compatible endpoint)
# ---------------------------------------------------------------------------
# Product images uploaded through the admin are pushed to a Supabase Storage
# bucket; the resulting public URL is written into ProductImage.image_url, so
# the schema's `image_url TEXT` column stays the single source of truth and
# existing external URLs keep working.

SUPABASE_URL = env('SUPABASE_URL', '')
SUPABASE_BUCKET = env('SUPABASE_BUCKET', 'product-images')
SUPABASE_S3_ENDPOINT = env('SUPABASE_S3_ENDPOINT', '')
SUPABASE_S3_REGION = env('SUPABASE_S3_REGION', 'us-east-1')
SUPABASE_S3_ACCESS_KEY_ID = env('SUPABASE_S3_ACCESS_KEY_ID', '')
SUPABASE_S3_SECRET_ACCESS_KEY = env('SUPABASE_S3_SECRET_ACCESS_KEY', '')

# True once every value the uploader needs is present. The admin hides the
# upload widget when this is False, so the project still runs without Storage.
SUPABASE_STORAGE_ENABLED = all([
    SUPABASE_URL,
    SUPABASE_S3_ENDPOINT,
    SUPABASE_S3_ACCESS_KEY_ID,
    SUPABASE_S3_SECRET_ACCESS_KEY,
])

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': SUPABASE_BUCKET,
            'endpoint_url': SUPABASE_S3_ENDPOINT,
            'region_name': SUPABASE_S3_REGION,
            'access_key': SUPABASE_S3_ACCESS_KEY_ID,
            'secret_key': SUPABASE_S3_SECRET_ACCESS_KEY,
            'file_overwrite': False,
            'default_acl': None,
            'querystring_auth': False,
            'signature_version': 's3v4',
            'addressing_style': 'path',
        },
    } if SUPABASE_STORAGE_ENABLED else {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------------------------------
# Production hardening (all inert while DEBUG=True)
# ---------------------------------------------------------------------------
# Render terminates TLS at its proxy and forwards this header, so Django knows
# the original request was HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Render injects RENDER_EXTERNAL_HOSTNAME with the service's own hostname.
RENDER_HOSTNAME = env('RENDER_EXTERNAL_HOSTNAME', '')
if RENDER_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    f'https://{host}' for host in ALLOWED_HOSTS
    if host not in ('localhost', '127.0.0.1', 'testserver')
]

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------
# Nothing in the catalogue sends mail (the contact form is presentational), but
# Django refuses to start with DEBUG=False on a console backend. Point at real
# SMTP by setting EMAIL_HOST/EMAIL_HOST_USER/EMAIL_HOST_PASSWORD; without them
# production discards mail rather than crashing. Note that admin password
# reset will not deliver until SMTP is configured.
# Lowercase: an uppercase EMAIL_HOST would be read as the deprecated
# Django setting, which may not coexist with MAILERS.
email_host = env('EMAIL_HOST', '')

if email_host:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'HOST': email_host,
            'PORT': int(env('EMAIL_PORT', '587')),
            'USERNAME': env('EMAIL_HOST_USER', ''),
            'PASSWORD': env('EMAIL_HOST_PASSWORD', ''),
            'USE_TLS': True,
        }
    }
elif DEBUG:
    MAILERS = {'default': {'BACKEND': 'django.core.mail.backends.console.EmailBackend'}}
else:
    MAILERS = {'default': {'BACKEND': 'django.core.mail.backends.dummy.EmailBackend'}}
    # Django treats any non-SMTP backend as a deployment error and refuses to
    # boot. This project sends no mail, so the dummy backend is deliberate --
    # silenced rather than left to crash the container on start.
    # Consequence: admin password reset cannot deliver. Set EMAIL_HOST (and
    # EMAIL_HOST_USER / EMAIL_HOST_PASSWORD) to switch to real SMTP; this
    # branch and the silence then both fall away automatically.
    SILENCED_SYSTEM_CHECKS = ['mail.E001']

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', 'no-reply@woodora.example')
