# Generated by Django 6.1 on 2026-09-07 11:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_search_vector_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_products_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
